### ISSUE TITLE
Better readme regarding status and using projects Kanban

### ISSUE THREAD

**Issue by aminya** [YingboMa/JuliaBLAS.jl#12]
This project is very intresting, however, because of lack of readme, and also a project kanban the progress is not known so other developers cannot help much in developing.

**Comment by YingboMa** [comment]
I don't plan to use project Kanban. Why aren't GitHub issues suffice?

**Comment by aminya** [comment]
Becuase In Projects you can create notes, that may not worth opening an issue. Also, every Github user can open an issue, but the owners can only change projects. All the big repositories have projects.

All in all, it helps getting more developers involved.

What about Readme and a docs folder (made from Documenter)?
