### ISSUE TITLE
Benchmark on Integers, and other types beyond Floats

### ISSUE THREAD

**Issue by oxinabox** [YingboMa/JuliaBLAS.jl#2]
Over https://github.com/SimonDanisch/julia-challenge/issues/1#issuecomment-421004798

@mratsim pointed out that
to get great performance for integers,
in https://github.com/mratsim/Arraymancer#micro-benchmark-int64-matrix-multiplication
A BLAS that specializes on integers is required.

Which this is.
And right now, 
JuliaBLAS outperforms 
`LinearAlgebra.generic_matmatmul`
for Integer matrixes.

And in time will be able to match the Arraymancer performance.

```
julia> using BenchmarkTools, LinearAlgebra, JuliaBLAS

julia> imat() = (rand(1:10_000_000, (1500,1500)))
imat (generic function with 1 method)

julia> fmat() = (10_000_000 * 10rand(Float64, (1500,1500)))
fmat (generic function with 1 method)

###########################
julia> @btime mul!($(0fmat()), $(fmat()), $(fmat()));
  198.536 ms (0 allocations: 0 bytes)

julia> @btime mymul!($(0fmat()), $(fmat()), $(fmat()));
  1.208 s (836006 allocations: 23.64 MiB)

julia> @btime mul!($(0imat()), $(imat()), $(imat()));
  5.266 s (6 allocations: 336 bytes)

julia> @btime mymul!($(0imat()), $(imat()), $(imat()));
  4.048 s (836006 allocations: 23.64 MiB)

```

**Comment by YingboMa** [comment]
Should be solved by #10
